"""
Download and preprocess super-resolution dataset.

This script reads the dataset manifest generated by create_sr_dataset.py and:
1. Downloads Sentinel-2 images and PlanetScope orders
2. Standardizes PlanetScope orders to a fixed 512x512 raster grid
3. Prepares data ready for training
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd
import rasterio
from rasterio.transform import from_origin
from rasterio.warp import reproject
from tqdm import tqdm

from .config import config_download
from .constants import (
    PATCH_SIZE_METERS,
    PATCH_SIZE_PIXELS,
    PLANETSCOPE_PRODUCT_BUNDLE,
)
from .planetscope import PlanetScopeManager
from .sentinel2 import Sentinel2Manager
from common.dataset_utils import ensure_directory, setup_logger


def download_sentinel2_images(sample_metadata, sample_dir, logger, sentinel2_manager, count):
    """Download Sentinel-2 images for a sample."""
    try:
        s2_images = sentinel2_manager.retrieve_images(
            sample_metadata["latitude"],
            sample_metadata["longitude"],
            sample_metadata["date_range_start"],
            sample_metadata["date_range_end"],
            count,
        )

        if not s2_images:
            logger.warning(
                f"No Sentinel-2 images found for location "
                f"({sample_metadata['latitude']}, {sample_metadata['longitude']})"
            )
            return False

        s2_dir = ensure_directory(sample_dir / "sentinel2")

        for index, img_info in enumerate(s2_images):
            date_str = img_info.get("date", "unknown").split("T")[0]
            logger.info(f"Processing Sentinel-2 image {index + 1}/{len(s2_images)}")

            image = sentinel2_manager.get_image_by_index(
                sample_metadata["latitude"],
                sample_metadata["longitude"],
                sample_metadata["date_range_start"],
                sample_metadata["date_range_end"],
                index,
            )

            if image is None:
                logger.warning(f"Failed to retrieve Sentinel-2 image at index {index}")
                continue

            output_file = s2_dir / f"sentinel2_{index:02d}_{date_str}.tif"
            if sentinel2_manager.download_image(
                image,
                sample_metadata["latitude"],
                sample_metadata["longitude"],
                output_file,
            ):
                logger.info(f"Downloaded Sentinel-2 image {index}: {output_file.name}")
            else:
                logger.error(f"Failed to download Sentinel-2 image {index}")
                return False

        return True

    except Exception as exc:
        logger.error(f"Failed to download Sentinel-2 images: {exc}")
        return False


def _build_target_transform(sample_metadata: Dict) -> tuple:
    origin_x = float(sample_metadata["target_origin_x"])
    origin_y = float(sample_metadata["target_origin_y"])
    pixel_size = float(sample_metadata.get("patch_size_meters", PATCH_SIZE_METERS)) / float(
        sample_metadata.get("patch_size_pixels", PATCH_SIZE_PIXELS)
    )
    transform = from_origin(origin_x, origin_y + float(sample_metadata.get("patch_size_meters", PATCH_SIZE_METERS)), pixel_size, pixel_size)
    return transform, pixel_size


def standardize_planetscope_patch(source_file: Path, output_file: Path, sample_metadata: Dict, logger) -> bool:
    """Warp a downloaded PlanetScope raster to the fixed manifest patch grid."""
    try:
        with rasterio.open(source_file) as src:
            source_data = src.read()
            target_transform, pixel_size = _build_target_transform(sample_metadata)
            target_shape = (
                int(sample_metadata.get("patch_size_pixels", PATCH_SIZE_PIXELS)),
                int(sample_metadata.get("patch_size_pixels", PATCH_SIZE_PIXELS)),
            )
            target_profile = src.profile.copy()
            target_profile.update(
                {
                    "driver": "GTiff",
                    "height": target_shape[0],
                    "width": target_shape[1],
                    "transform": target_transform,
                    "crs": sample_metadata["alignment_crs"],
                    "compress": "lzw",
                }
            )

            aligned_data = np.zeros((source_data.shape[0], target_shape[0], target_shape[1]), dtype=source_data.dtype)

            reproject(
                source_data,
                aligned_data,
                src_transform=src.transform,
                src_crs=src.crs,
                dst_transform=target_transform,
                dst_crs=sample_metadata["alignment_crs"],
                resampling=rasterio.enums.Resampling.bilinear,
            )

            with rasterio.open(output_file, "w", **target_profile) as dst:
                dst.write(aligned_data)

        logger.info(
            "Standardized PlanetScope raster %s to %sx%s at %.2fm pixels",
            source_file.name,
            target_shape[1],
            target_shape[0],
            pixel_size,
        )
        return True
    except Exception as exc:
        logger.error(f"Failed to standardize PlanetScope patch {source_file}: {exc}")
        return False


def download_planetscope_order(sample_metadata, sample_dir, logger, planetscope_manager):
    """Create and download a clipped PlanetScope order for a sample."""
    try:
        planet_item_ids = sample_metadata.get("planet_item_ids") or []
        if isinstance(planet_item_ids, str):
            planet_item_ids = json.loads(planet_item_ids)

        aoi_geometry = sample_metadata.get("planet_aoi_geojson")
        if isinstance(aoi_geometry, str):
            aoi_geometry = json.loads(aoi_geometry)

        if not planet_item_ids or not aoi_geometry:
            logger.warning(f"Missing PlanetScope order inputs for location {sample_metadata['location_id']}")
            return False

        order_id = sample_metadata.get("planet_order_id")
        if not order_id:
            order_name = f"sr-patch-{int(sample_metadata['location_id']):06d}"
            order_response = planetscope_manager.create_order(
                planet_item_ids,
                aoi_geometry,
                sample_metadata["alignment_crs"],
                order_name,
            )
            order_id = order_response.get("id")
            if not order_id:
                logger.error(f"Planet order creation did not return an order id for sample {sample_metadata['location_id']}")
                return False
            sample_metadata["planet_order_id"] = order_id

        order = planetscope_manager.wait_for_order(order_id)
        if not order:
            logger.error(f"Planet order {order_id} did not complete successfully")
            return False

        ps_dir = ensure_directory(sample_dir / "planetscope")
        order_dir = ensure_directory(ps_dir / order_id)
        downloaded_paths = planetscope_manager.download_order_results(order, order_dir)
        if not downloaded_paths:
            logger.error(f"No PlanetScope results downloaded for order {order_id}")
            return False

        raster_candidates = [path for path in downloaded_paths if path.suffix.lower() in {".tif", ".tiff"}]
        if not raster_candidates:
            logger.error(f"No raster outputs found for Planet order {order_id}")
            return False

        source_raster = raster_candidates[0]
        standardized_file = ps_dir / f"planetscope_{int(sample_metadata['location_id']):06d}.tif"
        if not standardize_planetscope_patch(source_raster, standardized_file, sample_metadata, logger):
            return False

        sample_metadata["planet_order_id"] = order_id
        sample_metadata["planet_product_bundle"] = PLANETSCOPE_PRODUCT_BUNDLE
        sample_metadata["planetscope_download_dir"] = str(order_dir)
        sample_metadata["planetscope_standardized_file"] = str(standardized_file)
        return True
    except Exception as exc:
        logger.error(f"Failed to download PlanetScope order: {exc}")
        return False


def download_sample(
    row: pd.Series,
    data_dir: Path,
    logger,
    sentinel2_manager: Sentinel2Manager,
    planetscope_manager: PlanetScopeManager,
) -> bool:
    """Download imagery for a single manifest row."""
    location_id = int(row["location_id"])
    sample_dir = ensure_directory(data_dir / f"sample_{location_id:06d}")

    sample_metadata_file = sample_dir / "sample_metadata.json"
    if sample_metadata_file.exists():
        logger.info(f"Skipping sample {location_id}: checkpoint already exists")
        return True

    try:
        sample_metadata = {
            "location_id": location_id,
            "latitude": float(row["latitude"]),
            "longitude": float(row["longitude"]),
            "province": str(row.get("province", row.get("ecoregion", "global"))),
            "season_id": int(row.get("season_id", 0)),
            "environment_class": str(row.get("environment_class", "")),
            "depth_class": str(row.get("depth_class", "")),
            "depth_m": float(row.get("depth_m", 0.0)),
            "turbidity_class": str(row.get("turbidity_class", "")),
            "turbidity_index": float(row.get("turbidity_index", 0.0)),
            "date_range_start": str(row["date_range_start"]),
            "date_range_end": str(row["date_range_end"]),
            "alignment_crs": str(row["alignment_crs"]),
            "patch_size_pixels": int(row.get("patch_size_pixels", PATCH_SIZE_PIXELS)),
            "patch_size_meters": float(row.get("patch_size_meters", PATCH_SIZE_METERS)),
            "target_origin_x": float(row.get("target_origin_x", 0.0)),
            "target_origin_y": float(row.get("target_origin_y", 0.0)),
            "planet_item_ids": row.get("planet_item_ids", []),
            "planet_order_id": str(row.get("planet_order_id", "")),
            "planet_product_bundle": str(row.get("planet_product_bundle", PLANETSCOPE_PRODUCT_BUNDLE)),
            "planet_aoi_geojson": row.get("planet_aoi_geojson", {}),
            "sentinel2_count": int(row.get("sentinel2_count", 0)),
            "planetscope_count": int(row.get("planetscope_count", 1)),
        }

        s2_count = int(row.get("sentinel2_count", 0))
        s2_ok = True
        if s2_count > 0:
            s2_ok = download_sentinel2_images(
                sample_metadata,
                sample_dir,
                logger,
                sentinel2_manager,
                s2_count,
            )

        ps_ok = download_planetscope_order(
            sample_metadata,
            sample_dir,
            logger,
            planetscope_manager,
        )

        if s2_ok and ps_ok:
            with open(sample_metadata_file, "w") as file_handle:
                json.dump(sample_metadata, file_handle, indent=2, default=str)
            return True

        return False
    except Exception as exc:
        logger.error(f"Failed to download sample {location_id}: {exc}")
        return False


def download_dataset():
    """Download and preprocess the dataset from a manifest."""
    config = config_download()
    logger = setup_logger("SRDatasetDownloader", config.metadata_dir / "download.log")

    manifest = pd.read_csv(config.manifest_file)

    sentinel2_manager = Sentinel2Manager(
        config.load_gee_credentials(), config.load_gee_project(), turbidity_raster=getattr(config, "turbidity_file", None)
    )
    planetscope_manager = PlanetScopeManager(config.load_planet_api_key())

    data_dir = ensure_directory(config.data_dir)

    successes = 0
    for _, row in tqdm(manifest.iterrows(), total=len(manifest), desc="Downloading samples"):
        if download_sample(row, data_dir, logger, sentinel2_manager, planetscope_manager):
            successes += 1

    logger.info("Downloaded %s/%s samples", successes, len(manifest))
    print(f"Downloaded {successes}/{len(manifest)} samples")


if __name__ == "__main__":
    download_dataset()
