"""
Download and preprocess super-resolution dataset.

This script reads the dataset manifest generated by create_sr_dataset.py and:
1. Downloads the low-res multi-image stack and the high-res target image
2. Standardizes the high-res image to a fixed pixel grid matching the manifest
3. Prepares data ready for training
"""

from __future__ import annotations

import json
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict

import numpy as np
import pandas as pd
import rasterio
from rasterio.transform import from_origin
from rasterio.warp import reproject
from tqdm import tqdm

from .config import config_download
from .constants import (
    DEFAULT_PATCH_SIZE_METERS,
    LOWRES_MIN_IMAGES,
    PATCH_SIZE_PIXELS,
)
from common.landsat import LANDSAT_OFFSET, LANDSAT_SCALE
from common.gee_satellite import GEESatelliteManager
from .satellites import (
    DEFAULT_HIGHRES_SATELLITE,
    DEFAULT_LOWRES_SATELLITE,
    HIGHRES_SATELLITES,
    LOWRES_SATELLITES,
    build_manager,
)
from common.dataset_utils import ensure_directory, setup_logger

# Margin applied around a patch's footprint when downloading the source raster
# for a GEE-backed high-res image, before it gets warped onto the exact
# manifest grid. Guards against clipping near the patch edges/corners.
HIGHRES_DOWNLOAD_MARGIN = 1.5

# Scene quality thresholds applied to raw DN downloads (scale/offset applied inline).
# These are intentionally conservative (high) to avoid false-positives on turbid
# coastal/estuarine water, which can have NIR 0.05–0.20 from suspended sediment.
# The retrospective check_dataset --check-quality uses lower thresholds for human review.
_S2_SCALE         = 1e-4   # Sentinel-2 L2A: reflectance = DN * 0.0001
_GLINT_NIR_THRESH = 0.25   # NIR threshold for glint check (both NIR and Blue must exceed their thresholds)
_GLINT_MIN_BLUE   = 0.12   # glint lifts all bands; turbid water has high NIR but low Blue (≤ ~0.12)
_HAZE_BLUE_THRESH = 0.25   # mean blue > 25 % → severe atmospheric haze (NIR usually stays low)
_LS_NIR_BAND      = 5      # Landsat SR_B5 (865 nm)
_LS_BLUE_BAND     = 2      # Landsat SR_B2 (482 nm)
_LS_QA_BAND       = 8      # Landsat QA_PIXEL band index in our download
_S2_NIR_BAND      = 8      # Sentinel-2 B8 (842 nm)
_S2_BLUE_BAND     = 2      # Sentinel-2 B2 (490 nm)
_NODATA_FRAC_MAX  = 0.20   # reject LR image if >20% of pixels are nodata (swath edge)
_CLOUD_FRAC_MAX   = 0.10   # reject Landsat image if >10% of valid pixels are cloud (QA_PIXEL bit 3)
_HR_NODATA_MAX    = 0.10   # reject HR patch if >10% nodata after standardization


def _check_image_quality(
    path: Path,
    nir_band: int,
    blue_band: int,
    scale: float,
    offset: float = 0.0,
) -> str:
    """Return 'glint', 'haze', or '' after applying scale/offset to get reflectance.

    Skips pixels where reflectance <= 0 (fill / nodata after scale/offset).
    Returns '' (clean) when bands are missing or on read error.
    """
    try:
        with rasterio.open(path) as src:
            def _mean(bidx: int):
                if src.count < bidx:
                    return None
                raw = src.read(bidx).astype(np.float32)
                nodata = src.nodata
                refl = raw * scale + offset
                mask = refl > 0
                if nodata is not None:
                    mask &= raw != nodata
                valid = refl[mask]
                return float(valid.mean()) if valid.size > 0 else None

            nir  = _mean(nir_band)
            blue = _mean(blue_band)
            if nir is not None and blue is not None and nir > _GLINT_NIR_THRESH and blue > _GLINT_MIN_BLUE:
                return "glint"
            if blue is not None and blue > _HAZE_BLUE_THRESH:
                return "haze"
    except Exception:
        pass
    return ""


def _check_landsat_coverage(path: Path) -> str:
    """Return 'nodata' (swath edge) or 'cloud' (QA_PIXEL), or '' if clean.

    Nodata fraction uses band 1 (SR_B1); cloud fraction uses QA_PIXEL bit 3.
    Both are checked against conservative thresholds so turbid/dark scenes are
    not falsely rejected.
    """
    try:
        with rasterio.open(path) as src:
            b1     = src.read(1)
            nodata = src.nodata
            nd_mask = (b1 == nodata) if nodata is not None else (b1 == 0)
            if nd_mask.mean() > _NODATA_FRAC_MAX:
                return "nodata"
            if src.count >= _LS_QA_BAND:
                qa         = src.read(_LS_QA_BAND)
                valid_mask = ~nd_mask
                if valid_mask.sum() > 0:
                    cloud_frac = ((qa >> 3) & 1)[valid_mask].mean()
                    if cloud_frac > _CLOUD_FRAC_MAX:
                        return "cloud"
    except Exception:
        pass
    return ""


def _check_hr_coverage(path: Path) -> str:
    """Return 'nodata' if the standardized HR patch has too many nodata pixels, else ''."""
    try:
        with rasterio.open(path) as src:
            b = src.read(2)   # B2 (Blue) is always present in both S2 and Landsat
            nodata = src.nodata
            nd_mask = (b == nodata) if nodata is not None else (b == 0)
            if nd_mask.mean() > _HR_NODATA_MAX:
                return "nodata"
    except Exception:
        pass
    return ""


def _lowres_files_present(sample_dir: Path, expected_count: int, lowres_key: str) -> bool:
    """Check whether the expected low-res rasters already exist on disk."""
    if expected_count <= 0:
        return True
    lowres_dir = sample_dir / lowres_key
    if not lowres_dir.exists():
        return False
    return len(list(lowres_dir.glob(f"{lowres_key}_*.tif"))) >= expected_count


def _highres_standardized_file(sample_dir: Path, location_id: int, highres_key: str) -> Path:
    return sample_dir / highres_key / f"{highres_key}_{location_id:06d}.tif"


def _highres_order_checkpoint_file(sample_dir: Path, highres_key: str) -> Path:
    return sample_dir / highres_key / "order_id.json"


def _load_highres_order_id(sample_dir: Path, highres_key: str) -> str:
    checkpoint_file = _highres_order_checkpoint_file(sample_dir, highres_key)
    if not checkpoint_file.exists():
        return ""
    try:
        with open(checkpoint_file) as file_handle:
            return json.load(file_handle).get("order_id", "")
    except (json.JSONDecodeError, OSError):
        return ""


def _save_highres_order_id(sample_dir: Path, highres_key: str, order_id: str) -> None:
    checkpoint_file = _highres_order_checkpoint_file(sample_dir, highres_key)
    checkpoint_file.parent.mkdir(parents=True, exist_ok=True)
    with open(checkpoint_file, "w") as file_handle:
        json.dump({"order_id": order_id}, file_handle)


def _clear_highres_order_id(sample_dir: Path, highres_key: str) -> None:
    _highres_order_checkpoint_file(sample_dir, highres_key).unlink(missing_ok=True)


def _download_buffer_meters(patch_size_meters: float, margin: float = HIGHRES_DOWNLOAD_MARGIN) -> float:
    """Meters of buffer needed around a point to cover a patch of *patch_size_meters*.

    Used as a true geodesic radius for ee.Geometry.buffer(), which is
    latitude-independent, so no longitude-compression correction is needed here.
    """
    return (patch_size_meters / 2.0) * margin


def _raster_is_empty(path: Path) -> bool:
    """Return True if band 1 of *path* is entirely zero or equal to the nodata value."""
    try:
        with rasterio.open(path) as src:
            data = src.read(1)
            nodata = src.nodata
            if nodata is not None:
                return bool(np.all(data == nodata))
            return bool(np.all(data == 0))
    except Exception:
        return True


def download_lowres_images(sample_metadata, sample_dir, logger, lowres_manager, count, lowres_key):
    """Download the low-resolution multi-image stack for a sample."""
    try:
        # Same AOI polygon create_sr_dataset.py used to validate low-res availability for
        # this sample (stored under "highres_aoi_geojson" since it's also the order/export
        # footprint for the high-res image). Re-querying with just the center point instead
        # of this polygon can find fewer images than creation did - e.g. when the point sits
        # right at a satellite scene/path boundary - so reuse the same search geometry here.
        aoi_geometry = sample_metadata.get("highres_aoi_geojson")
        if isinstance(aoi_geometry, str):
            aoi_geometry = json.loads(aoi_geometry)

        lowres_images = lowres_manager.retrieve_images(
            sample_metadata["latitude"],
            sample_metadata["longitude"],
            sample_metadata["date_range_start"],
            sample_metadata["date_range_end"],
            count,
            aoi_geometry=aoi_geometry,
        )

        if not lowres_images:
            logger.warning(
                f"No {lowres_key} images found for location "
                f"({sample_metadata['latitude']}, {sample_metadata['longitude']})"
            )
            return False

        lowres_dir = ensure_directory(sample_dir / lowres_key)

        # LR uses exactly the target patch extent (half-side as radius) with no extra
        # margin — the 1.5× margin is only for HR to give reprojection room.  Using the
        # margin here makes LR cover 1.5× more area than HR, which breaks paired training.
        patch_size_meters = float(sample_metadata.get("patch_size_meters", DEFAULT_PATCH_SIZE_METERS))
        buffer_meters = patch_size_meters / 2.0

        lat = sample_metadata["latitude"]
        lon = sample_metadata["longitude"]
        total = len(lowres_images)

        def _download_one(index: int, img_info: dict) -> str:
            """Download and validate one LR image. Returns 'ok', 'skip:<reason>', or 'fail'."""
            date_str = img_info.get("date", "unknown").split("T")[0]
            image = lowres_manager.get_image_by_asset_id(img_info["asset_id"])
            if image is None:
                logger.warning(f"Failed to resolve {lowres_key} image at index {index}")
                return "skip:unresolved"

            output_file = lowres_dir / f"{lowres_key}_{index:02d}_{date_str}.tif"
            if not lowres_manager.download_image(image, lat, lon, output_file, buffer_meters=buffer_meters):
                logger.error(f"Failed to download {lowres_key} image {index}")
                return "fail"

            if _raster_is_empty(output_file):
                logger.warning(
                    f"{lowres_key} image {index} ({output_file.name}) is all-zero — "
                    f"fill data at this location; rejecting sample so it can be retried"
                )
                output_file.unlink(missing_ok=True)
                return "fail:empty"

            coverage_issue = _check_landsat_coverage(output_file)
            if coverage_issue == "nodata":
                logger.warning(
                    f"{lowres_key} image {index} ({output_file.name}): >20% nodata "
                    f"(swath edge) — skipping this acquisition"
                )
                output_file.unlink(missing_ok=True)
                return "skip:nodata"
            if coverage_issue == "cloud":
                logger.warning(
                    f"{lowres_key} image {index} ({output_file.name}): >10% cloud pixels "
                    f"(QA_PIXEL) — skipping this acquisition"
                )
                output_file.unlink(missing_ok=True)
                return "skip:cloud"

            issue = _check_image_quality(
                output_file, _LS_NIR_BAND, _LS_BLUE_BAND, LANDSAT_SCALE, LANDSAT_OFFSET
            )
            if issue:
                logger.warning(
                    f"{lowres_key} image {index} ({output_file.name}): {issue} detected "
                    f"(NIR/blue mean too high for a water scene) — skipping this acquisition"
                )
                output_file.unlink(missing_ok=True)
                return f"skip:{issue}"

            logger.info(f"Downloaded {lowres_key} image {index + 1}/{total}: {output_file.name}")
            return "ok"

        # Download all LR images concurrently (GEE server-side work is the bottleneck;
        # 4 workers saturates the per-user GEE concurrent-request limit safely).
        with ThreadPoolExecutor(max_workers=4) as pool:
            results = dict(zip(
                range(total),
                pool.map(_download_one, range(total), lowres_images),
            ))

        if any(r.startswith("fail") for r in results.values()):
            return False

        kept = len(sorted(lowres_dir.glob(f"{lowres_key}_*.tif")))
        if kept < LOWRES_MIN_IMAGES:
            logger.warning(
                f"Only {kept} clean {lowres_key} image(s) after quality filtering "
                f"(need {LOWRES_MIN_IMAGES}); rejecting sample"
            )
            return False
        return True

    except Exception as exc:
        logger.error(f"Failed to download {lowres_key} images: {exc}")
        return False


def _build_target_transform(sample_metadata: Dict) -> tuple:
    origin_x = float(sample_metadata["target_origin_x"])
    origin_y = float(sample_metadata["target_origin_y"])
    patch_size_meters = float(sample_metadata.get("patch_size_meters", DEFAULT_PATCH_SIZE_METERS))
    pixel_size = patch_size_meters / float(sample_metadata.get("patch_size_pixels", PATCH_SIZE_PIXELS))
    transform = from_origin(origin_x, origin_y + patch_size_meters, pixel_size, pixel_size)
    return transform, pixel_size


def standardize_highres_patch(source_file: Path, output_file: Path, sample_metadata: Dict, logger) -> bool:
    """Warp a downloaded high-res raster to the fixed manifest patch grid."""
    try:
        with rasterio.open(source_file) as src:
            source_data = src.read()
            target_transform, pixel_size = _build_target_transform(sample_metadata)
            target_shape = (
                int(sample_metadata.get("patch_size_pixels", PATCH_SIZE_PIXELS)),
                int(sample_metadata.get("patch_size_pixels", PATCH_SIZE_PIXELS)),
            )
            target_profile = src.profile.copy()
            target_profile.update(
                {
                    "driver": "GTiff",
                    "height": target_shape[0],
                    "width": target_shape[1],
                    "transform": target_transform,
                    "crs": sample_metadata["alignment_crs"],
                    "compress": "lzw",
                }
            )

            aligned_data = np.zeros((source_data.shape[0], target_shape[0], target_shape[1]), dtype=source_data.dtype)

            reproject(
                source_data,
                aligned_data,
                src_transform=src.transform,
                src_crs=src.crs,
                dst_transform=target_transform,
                dst_crs=sample_metadata["alignment_crs"],
                resampling=rasterio.enums.Resampling.bilinear,
            )

            with rasterio.open(output_file, "w", **target_profile) as dst:
                dst.write(aligned_data)

        logger.info(
            "Standardized high-res raster %s to %sx%s at %.2fm pixels",
            source_file.name,
            target_shape[1],
            target_shape[0],
            pixel_size,
        )
        return True
    except Exception as exc:
        logger.error(f"Failed to standardize high-res patch {source_file}: {exc}")
        return False


def download_highres_gee_image(sample_metadata, sample_dir, logger, highres_manager, highres_key):
    """Download and standardize a single GEE-backed high-resolution image."""
    try:
        highres_item_ids = sample_metadata.get("highres_item_ids") or []
        if isinstance(highres_item_ids, str):
            highres_item_ids = json.loads(highres_item_ids)

        if not highres_item_ids:
            logger.warning(f"Missing high-res asset id for location {sample_metadata['location_id']}")
            return False

        asset_id = highres_item_ids[0]
        image = highres_manager.get_image_by_asset_id(asset_id)
        if image is None:
            logger.error(f"Failed to resolve high-res image {asset_id}")
            return False

        # Raw download lives in a nested "raw" subfolder so tile_dataset.py's
        # top-level glob of the role directory only picks up the standardized file.
        raw_dir = ensure_directory(sample_dir / highres_key / "raw")
        raw_file = raw_dir / f"{highres_key}_raw_{int(sample_metadata['location_id']):06d}.tif"

        patch_size_meters = float(sample_metadata.get("patch_size_meters", DEFAULT_PATCH_SIZE_METERS))
        buffer_meters = _download_buffer_meters(patch_size_meters)

        if not highres_manager.download_image(
            image,
            sample_metadata["latitude"],
            sample_metadata["longitude"],
            raw_file,
            buffer_meters=buffer_meters,
        ):
            return False

        if _raster_is_empty(raw_file):
            logger.warning(
                f"High-res raw download for {asset_id} is all-zero — "
                f"fill data at this location; rejecting sample"
            )
            raw_file.unlink(missing_ok=True)
            return False

        standardized_file = _highres_standardized_file(sample_dir, sample_metadata["location_id"], highres_key)
        if not standardize_highres_patch(raw_file, standardized_file, sample_metadata, logger):
            return False

        if _check_hr_coverage(standardized_file) == "nodata":
            logger.warning(
                f"High-res image {asset_id}: >10% nodata after standardization "
                f"(source tile doesn't fully cover the target patch) — rejecting sample"
            )
            standardized_file.unlink(missing_ok=True)
            return False

        issue = _check_image_quality(standardized_file, _S2_NIR_BAND, _S2_BLUE_BAND, _S2_SCALE)
        if issue:
            logger.warning(
                f"High-res image {asset_id}: {issue} detected (NIR/blue mean too high for "
                f"a water scene) — rejecting sample. To skip permanently, run: "
                f"drop_samples ... {int(sample_metadata['location_id'])}"
            )
            standardized_file.unlink(missing_ok=True)
            return False

        sample_metadata["highres_standardized_file"] = str(standardized_file)
        return True
    except Exception as exc:
        logger.error(f"Failed to download high-res GEE image: {exc}")
        return False


def download_highres_planet_order(sample_metadata, sample_dir, logger, highres_manager, highres_key):
    """Create and download a clipped Planet order for the high-resolution image."""
    try:
        highres_item_ids = sample_metadata.get("highres_item_ids") or []
        if isinstance(highres_item_ids, str):
            highres_item_ids = json.loads(highres_item_ids)

        aoi_geometry = sample_metadata.get("highres_aoi_geojson")
        if isinstance(aoi_geometry, str):
            aoi_geometry = json.loads(aoi_geometry)

        if not highres_item_ids or not aoi_geometry:
            logger.warning(f"Missing Planet order inputs for location {sample_metadata['location_id']}")
            return False

        order_id = sample_metadata.get("highres_order_id") or _load_highres_order_id(sample_dir, highres_key)
        if order_id:
            logger.info(f"Checking existing Planet order {order_id} for sample {sample_metadata['location_id']}")
        else:
            order_name = f"sr-patch-{int(sample_metadata['location_id']):06d}"
            order_response = highres_manager.create_order(
                highres_item_ids,
                aoi_geometry,
                sample_metadata["alignment_crs"],
                order_name,
            )
            order_id = order_response.get("id")
            if not order_id:
                logger.error(f"Planet order creation did not return an order id for sample {sample_metadata['location_id']}")
                return False
            _save_highres_order_id(sample_dir, highres_key, order_id)
            logger.info(f"Placed Planet order {order_id} for sample {sample_metadata['location_id']}")
        sample_metadata["highres_order_id"] = order_id

        order = highres_manager.get_order(order_id)
        state = order.get("state")

        if state == "failed":
            logger.error(
                "Planet order %s for sample %s failed: %s",
                order_id,
                sample_metadata["location_id"],
                order.get("error_hints") or order.get("last_message", "unknown error"),
            )
            _clear_highres_order_id(sample_dir, highres_key)
            return False

        if state not in {"success", "partial"}:
            logger.info(
                f"Planet order {order_id} for sample {sample_metadata['location_id']} is still "
                f"'{state}'; will check again on the next run"
            )
            return False

        highres_dir = ensure_directory(sample_dir / highres_key)
        order_dir = ensure_directory(highres_dir / order_id)
        downloaded_paths = highres_manager.download_order_results(order, order_dir)
        if not downloaded_paths:
            logger.error(f"No PlanetScope results downloaded for order {order_id} (state={state})")
            return False

        raster_candidates = [path for path in downloaded_paths if path.suffix.lower() in {".tif", ".tiff"}]
        if not raster_candidates:
            logger.error(f"No raster outputs found for Planet order {order_id}")
            return False

        source_raster = next(
            (path for path in raster_candidates if "analyticms" in path.name.lower()),
            raster_candidates[0],
        )
        standardized_file = _highres_standardized_file(sample_dir, sample_metadata["location_id"], highres_key)
        if not standardize_highres_patch(source_raster, standardized_file, sample_metadata, logger):
            return False

        sample_metadata["highres_order_id"] = order_id
        sample_metadata["highres_download_dir"] = str(order_dir)
        sample_metadata["highres_standardized_file"] = str(standardized_file)
        return True
    except Exception as exc:
        logger.error(f"Failed to download Planet order: {exc}")
        return False


def download_sample(
    row: pd.Series,
    data_dir: Path,
    logger,
    lowres_manager,
    highres_manager,
    lowres_key: str,
    highres_key: str,
) -> bool:
    """Download imagery for a single manifest row."""
    location_id = int(row["location_id"])
    sample_dir = ensure_directory(data_dir / f"sample_{location_id:06d}")

    sample_metadata_file = sample_dir / "sample_metadata.json"
    if sample_metadata_file.exists():
        logger.info(f"Skipping sample {location_id}: checkpoint already exists")
        return True

    try:
        sample_metadata = {
            "location_id": location_id,
            "latitude": float(row["latitude"]),
            "longitude": float(row["longitude"]),
            "province": str(row.get("province", row.get("ecoregion", "global"))),
            "season_id": int(row.get("season_id", 0)),
            "environment_class": str(row.get("environment_class", "")),
            "depth_class": str(row.get("depth_class", "")),
            "depth_m": float(row.get("depth_m", 0.0)),
            "turbidity_class": str(row.get("turbidity_class", "")),
            "turbidity_index": float(row.get("turbidity_index", 0.0)),
            "date_range_start": str(row["date_range_start"]),
            "date_range_end": str(row["date_range_end"]),
            "alignment_crs": str(row["alignment_crs"]),
            "patch_size_pixels": int(row.get("patch_size_pixels", PATCH_SIZE_PIXELS)),
            "patch_size_meters": float(row.get("patch_size_meters", DEFAULT_PATCH_SIZE_METERS)),
            "target_origin_x": float(row.get("target_origin_x", 0.0)),
            "target_origin_y": float(row.get("target_origin_y", 0.0)),
            "lowres_satellite": lowres_key,
            "highres_satellite": highres_key,
            "highres_item_ids": row.get("highres_item_ids", []),
            "highres_order_id": "" if pd.isna(row.get("highres_order_id", "")) else str(row.get("highres_order_id", "")),
            "highres_product_bundle": str(row.get("highres_product_bundle", "")),
            "highres_aoi_geojson": row.get("highres_aoi_geojson", {}),
            "lowres_count": int(row.get("lowres_count", 0)),
            "highres_count": int(row.get("highres_count", 1)),
        }

        lowres_count = int(row.get("lowres_count", 0))
        lowres_ok = True
        if lowres_count > 0:
            if _lowres_files_present(sample_dir, lowres_count, lowres_key):
                logger.info(f"Sample {location_id}: {lowres_key} images already on disk, skipping download")
            else:
                lowres_ok = download_lowres_images(
                    sample_metadata,
                    sample_dir,
                    logger,
                    lowres_manager,
                    lowres_count,
                    lowres_key,
                )

        standardized_file = _highres_standardized_file(sample_dir, location_id, highres_key)
        if standardized_file.exists():
            logger.info(f"Sample {location_id}: high-res raster already on disk, skipping download")
            sample_metadata["highres_standardized_file"] = str(standardized_file)
            highres_ok = True
        elif isinstance(highres_manager, GEESatelliteManager):
            highres_ok = download_highres_gee_image(sample_metadata, sample_dir, logger, highres_manager, highres_key)
        else:
            highres_ok = download_highres_planet_order(sample_metadata, sample_dir, logger, highres_manager, highres_key)

        if lowres_ok and highres_ok:
            with open(sample_metadata_file, "w") as file_handle:
                json.dump(sample_metadata, file_handle, indent=2, default=str)
            return True

        return False
    except Exception as exc:
        logger.error(f"Failed to download sample {location_id}: {exc}")
        return False


def download_dataset():
    """Download and preprocess the dataset from a manifest."""
    config = config_download()
    logger = setup_logger("SRDatasetDownloader", config.metadata_dir / "download.log")

    manifest = pd.read_csv(config.manifest_file)

    lowres_managers = {}
    highres_managers = {}

    def get_lowres_manager(key):
        if key not in lowres_managers:
            lowres_managers[key] = build_manager(key, LOWRES_SATELLITES, config)
        return lowres_managers[key]

    def get_highres_manager(key):
        if key not in highres_managers:
            highres_managers[key] = build_manager(key, HIGHRES_SATELLITES, config)
        return highres_managers[key]

    data_dir = ensure_directory(config.data_dir)

    successes = 0
    for _, row in tqdm(manifest.iterrows(), total=len(manifest), desc="Downloading samples"):
        lowres_key = str(row.get("lowres_satellite") or config.lowres_satellite or DEFAULT_LOWRES_SATELLITE)
        highres_key = str(row.get("highres_satellite") or config.highres_satellite or DEFAULT_HIGHRES_SATELLITE)
        lowres_manager = get_lowres_manager(lowres_key)
        highres_manager = get_highres_manager(highres_key)
        if download_sample(row, data_dir, logger, lowres_manager, highres_manager, lowres_key, highres_key):
            successes += 1

    logger.info("Downloaded %s/%s samples", successes, len(manifest))
    print(f"Downloaded {successes}/{len(manifest)} samples")


if __name__ == "__main__":
    download_dataset()
