"""
Download and preprocess super-resolution dataset.

This script reads the dataset manifest generated by create_sr_dataset.py and:
1. Downloads the low-res multi-image stack and the high-res target image
2. Standardizes the high-res image to a fixed pixel grid matching the manifest
3. Prepares data ready for training
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict

import numpy as np
import pandas as pd
import rasterio
from rasterio.transform import from_origin
from rasterio.warp import reproject
from tqdm import tqdm

from .config import config_download
from .constants import (
    DEFAULT_PATCH_SIZE_METERS,
    PATCH_SIZE_PIXELS,
)
from .gee_satellite import GEESatelliteManager
from .satellites import (
    DEFAULT_HIGHRES_SATELLITE,
    DEFAULT_LOWRES_SATELLITE,
    HIGHRES_SATELLITES,
    LOWRES_SATELLITES,
    build_manager,
)
from common.dataset_utils import ensure_directory, setup_logger

# Margin applied around a patch's footprint when downloading the source raster
# for a GEE-backed high-res image, before it gets warped onto the exact
# manifest grid. Guards against clipping near the patch edges/corners.
HIGHRES_DOWNLOAD_MARGIN = 1.5


def _lowres_files_present(sample_dir: Path, expected_count: int, lowres_key: str) -> bool:
    """Check whether the expected low-res rasters already exist on disk."""
    if expected_count <= 0:
        return True
    lowres_dir = sample_dir / lowres_key
    if not lowres_dir.exists():
        return False
    return len(list(lowres_dir.glob(f"{lowres_key}_*.tif"))) >= expected_count


def _highres_standardized_file(sample_dir: Path, location_id: int, highres_key: str) -> Path:
    return sample_dir / highres_key / f"{highres_key}_{location_id:06d}.tif"


def _highres_order_checkpoint_file(sample_dir: Path, highres_key: str) -> Path:
    return sample_dir / highres_key / "order_id.json"


def _load_highres_order_id(sample_dir: Path, highres_key: str) -> str:
    checkpoint_file = _highres_order_checkpoint_file(sample_dir, highres_key)
    if not checkpoint_file.exists():
        return ""
    try:
        with open(checkpoint_file) as file_handle:
            return json.load(file_handle).get("order_id", "")
    except (json.JSONDecodeError, OSError):
        return ""


def _save_highres_order_id(sample_dir: Path, highres_key: str, order_id: str) -> None:
    checkpoint_file = _highres_order_checkpoint_file(sample_dir, highres_key)
    checkpoint_file.parent.mkdir(parents=True, exist_ok=True)
    with open(checkpoint_file, "w") as file_handle:
        json.dump({"order_id": order_id}, file_handle)


def _clear_highres_order_id(sample_dir: Path, highres_key: str) -> None:
    _highres_order_checkpoint_file(sample_dir, highres_key).unlink(missing_ok=True)


def _download_buffer_meters(patch_size_meters: float, margin: float = HIGHRES_DOWNLOAD_MARGIN) -> float:
    """Meters of buffer needed around a point to cover a patch of *patch_size_meters*.

    Used as a true geodesic radius for ee.Geometry.buffer(), which is
    latitude-independent, so no longitude-compression correction is needed here.
    """
    return (patch_size_meters / 2.0) * margin


def _raster_is_empty(path: Path) -> bool:
    """Return True if band 1 of *path* is entirely zero or equal to the nodata value."""
    try:
        with rasterio.open(path) as src:
            data = src.read(1)
            nodata = src.nodata
            if nodata is not None:
                return bool(np.all(data == nodata))
            return bool(np.all(data == 0))
    except Exception:
        return True


def download_lowres_images(sample_metadata, sample_dir, logger, lowres_manager, count, lowres_key):
    """Download the low-resolution multi-image stack for a sample."""
    try:
        # Same AOI polygon create_sr_dataset.py used to validate low-res availability for
        # this sample (stored under "highres_aoi_geojson" since it's also the order/export
        # footprint for the high-res image). Re-querying with just the center point instead
        # of this polygon can find fewer images than creation did - e.g. when the point sits
        # right at a satellite scene/path boundary - so reuse the same search geometry here.
        aoi_geometry = sample_metadata.get("highres_aoi_geojson")
        if isinstance(aoi_geometry, str):
            aoi_geometry = json.loads(aoi_geometry)

        lowres_images = lowres_manager.retrieve_images(
            sample_metadata["latitude"],
            sample_metadata["longitude"],
            sample_metadata["date_range_start"],
            sample_metadata["date_range_end"],
            count,
            aoi_geometry=aoi_geometry,
        )

        if not lowres_images:
            logger.warning(
                f"No {lowres_key} images found for location "
                f"({sample_metadata['latitude']}, {sample_metadata['longitude']})"
            )
            return False

        lowres_dir = ensure_directory(sample_dir / lowres_key)

        # Match the high-res target's ground footprint (not the satellite's generic
        # SPEC default buffer) so low-res/high-res pairs are aligned, and so Sentinel-2's
        # many bands don't blow past Earth Engine's 48MB synchronous download cap.
        patch_size_meters = float(sample_metadata.get("patch_size_meters", DEFAULT_PATCH_SIZE_METERS))
        buffer_meters = _download_buffer_meters(patch_size_meters)

        for index, img_info in enumerate(lowres_images):
            date_str = img_info.get("date", "unknown").split("T")[0]
            logger.info(f"Processing {lowres_key} image {index + 1}/{len(lowres_images)}")

            image = lowres_manager.get_image_by_asset_id(img_info["asset_id"])
            if image is None:
                logger.warning(f"Failed to resolve {lowres_key} image at index {index}")
                continue

            output_file = lowres_dir / f"{lowres_key}_{index:02d}_{date_str}.tif"
            if not lowres_manager.download_image(
                image,
                sample_metadata["latitude"],
                sample_metadata["longitude"],
                output_file,
                buffer_meters=buffer_meters,
            ):
                logger.error(f"Failed to download {lowres_key} image {index}")
                return False

            # Reject scenes that downloaded successfully but contain only fill/zero
            # pixels (e.g. Landsat swath gaps, partial S2 granules that intersect
            # the AOI but don't actually cover the patch location).
            if _raster_is_empty(output_file):
                logger.warning(
                    f"{lowres_key} image {index} ({output_file.name}) is all-zero — "
                    f"fill data at this location; rejecting sample so it can be retried"
                )
                output_file.unlink(missing_ok=True)
                return False

            logger.info(f"Downloaded {lowres_key} image {index}: {output_file.name}")

        return True

    except Exception as exc:
        logger.error(f"Failed to download {lowres_key} images: {exc}")
        return False


def _build_target_transform(sample_metadata: Dict) -> tuple:
    origin_x = float(sample_metadata["target_origin_x"])
    origin_y = float(sample_metadata["target_origin_y"])
    patch_size_meters = float(sample_metadata.get("patch_size_meters", DEFAULT_PATCH_SIZE_METERS))
    pixel_size = patch_size_meters / float(sample_metadata.get("patch_size_pixels", PATCH_SIZE_PIXELS))
    transform = from_origin(origin_x, origin_y + patch_size_meters, pixel_size, pixel_size)
    return transform, pixel_size


def standardize_highres_patch(source_file: Path, output_file: Path, sample_metadata: Dict, logger) -> bool:
    """Warp a downloaded high-res raster to the fixed manifest patch grid."""
    try:
        with rasterio.open(source_file) as src:
            source_data = src.read()
            target_transform, pixel_size = _build_target_transform(sample_metadata)
            target_shape = (
                int(sample_metadata.get("patch_size_pixels", PATCH_SIZE_PIXELS)),
                int(sample_metadata.get("patch_size_pixels", PATCH_SIZE_PIXELS)),
            )
            target_profile = src.profile.copy()
            target_profile.update(
                {
                    "driver": "GTiff",
                    "height": target_shape[0],
                    "width": target_shape[1],
                    "transform": target_transform,
                    "crs": sample_metadata["alignment_crs"],
                    "compress": "lzw",
                }
            )

            aligned_data = np.zeros((source_data.shape[0], target_shape[0], target_shape[1]), dtype=source_data.dtype)

            reproject(
                source_data,
                aligned_data,
                src_transform=src.transform,
                src_crs=src.crs,
                dst_transform=target_transform,
                dst_crs=sample_metadata["alignment_crs"],
                resampling=rasterio.enums.Resampling.bilinear,
            )

            with rasterio.open(output_file, "w", **target_profile) as dst:
                dst.write(aligned_data)

        logger.info(
            "Standardized high-res raster %s to %sx%s at %.2fm pixels",
            source_file.name,
            target_shape[1],
            target_shape[0],
            pixel_size,
        )
        return True
    except Exception as exc:
        logger.error(f"Failed to standardize high-res patch {source_file}: {exc}")
        return False


def download_highres_gee_image(sample_metadata, sample_dir, logger, highres_manager, highres_key):
    """Download and standardize a single GEE-backed high-resolution image."""
    try:
        highres_item_ids = sample_metadata.get("highres_item_ids") or []
        if isinstance(highres_item_ids, str):
            highres_item_ids = json.loads(highres_item_ids)

        if not highres_item_ids:
            logger.warning(f"Missing high-res asset id for location {sample_metadata['location_id']}")
            return False

        asset_id = highres_item_ids[0]
        image = highres_manager.get_image_by_asset_id(asset_id)
        if image is None:
            logger.error(f"Failed to resolve high-res image {asset_id}")
            return False

        # Raw download lives in a nested "raw" subfolder so tile_dataset.py's
        # top-level glob of the role directory only picks up the standardized file.
        raw_dir = ensure_directory(sample_dir / highres_key / "raw")
        raw_file = raw_dir / f"{highres_key}_raw_{int(sample_metadata['location_id']):06d}.tif"

        patch_size_meters = float(sample_metadata.get("patch_size_meters", DEFAULT_PATCH_SIZE_METERS))
        buffer_meters = _download_buffer_meters(patch_size_meters)

        if not highres_manager.download_image(
            image,
            sample_metadata["latitude"],
            sample_metadata["longitude"],
            raw_file,
            buffer_meters=buffer_meters,
        ):
            return False

        if _raster_is_empty(raw_file):
            logger.warning(
                f"High-res raw download for {asset_id} is all-zero — "
                f"fill data at this location; rejecting sample"
            )
            raw_file.unlink(missing_ok=True)
            return False

        standardized_file = _highres_standardized_file(sample_dir, sample_metadata["location_id"], highres_key)
        if not standardize_highres_patch(raw_file, standardized_file, sample_metadata, logger):
            return False

        sample_metadata["highres_standardized_file"] = str(standardized_file)
        return True
    except Exception as exc:
        logger.error(f"Failed to download high-res GEE image: {exc}")
        return False


def download_highres_planet_order(sample_metadata, sample_dir, logger, highres_manager, highres_key):
    """Create and download a clipped Planet order for the high-resolution image."""
    try:
        highres_item_ids = sample_metadata.get("highres_item_ids") or []
        if isinstance(highres_item_ids, str):
            highres_item_ids = json.loads(highres_item_ids)

        aoi_geometry = sample_metadata.get("highres_aoi_geojson")
        if isinstance(aoi_geometry, str):
            aoi_geometry = json.loads(aoi_geometry)

        if not highres_item_ids or not aoi_geometry:
            logger.warning(f"Missing Planet order inputs for location {sample_metadata['location_id']}")
            return False

        order_id = sample_metadata.get("highres_order_id") or _load_highres_order_id(sample_dir, highres_key)
        if order_id:
            logger.info(f"Checking existing Planet order {order_id} for sample {sample_metadata['location_id']}")
        else:
            order_name = f"sr-patch-{int(sample_metadata['location_id']):06d}"
            order_response = highres_manager.create_order(
                highres_item_ids,
                aoi_geometry,
                sample_metadata["alignment_crs"],
                order_name,
            )
            order_id = order_response.get("id")
            if not order_id:
                logger.error(f"Planet order creation did not return an order id for sample {sample_metadata['location_id']}")
                return False
            _save_highres_order_id(sample_dir, highres_key, order_id)
            logger.info(f"Placed Planet order {order_id} for sample {sample_metadata['location_id']}")
        sample_metadata["highres_order_id"] = order_id

        order = highres_manager.get_order(order_id)
        state = order.get("state")

        if state == "failed":
            logger.error(
                "Planet order %s for sample %s failed: %s",
                order_id,
                sample_metadata["location_id"],
                order.get("error_hints") or order.get("last_message", "unknown error"),
            )
            _clear_highres_order_id(sample_dir, highres_key)
            return False

        if state not in {"success", "partial"}:
            logger.info(
                f"Planet order {order_id} for sample {sample_metadata['location_id']} is still "
                f"'{state}'; will check again on the next run"
            )
            return False

        highres_dir = ensure_directory(sample_dir / highres_key)
        order_dir = ensure_directory(highres_dir / order_id)
        downloaded_paths = highres_manager.download_order_results(order, order_dir)
        if not downloaded_paths:
            logger.error(f"No PlanetScope results downloaded for order {order_id} (state={state})")
            return False

        raster_candidates = [path for path in downloaded_paths if path.suffix.lower() in {".tif", ".tiff"}]
        if not raster_candidates:
            logger.error(f"No raster outputs found for Planet order {order_id}")
            return False

        source_raster = next(
            (path for path in raster_candidates if "analyticms" in path.name.lower()),
            raster_candidates[0],
        )
        standardized_file = _highres_standardized_file(sample_dir, sample_metadata["location_id"], highres_key)
        if not standardize_highres_patch(source_raster, standardized_file, sample_metadata, logger):
            return False

        sample_metadata["highres_order_id"] = order_id
        sample_metadata["highres_download_dir"] = str(order_dir)
        sample_metadata["highres_standardized_file"] = str(standardized_file)
        return True
    except Exception as exc:
        logger.error(f"Failed to download Planet order: {exc}")
        return False


def download_sample(
    row: pd.Series,
    data_dir: Path,
    logger,
    lowres_manager,
    highres_manager,
    lowres_key: str,
    highres_key: str,
) -> bool:
    """Download imagery for a single manifest row."""
    location_id = int(row["location_id"])
    sample_dir = ensure_directory(data_dir / f"sample_{location_id:06d}")

    sample_metadata_file = sample_dir / "sample_metadata.json"
    if sample_metadata_file.exists():
        logger.info(f"Skipping sample {location_id}: checkpoint already exists")
        return True

    try:
        sample_metadata = {
            "location_id": location_id,
            "latitude": float(row["latitude"]),
            "longitude": float(row["longitude"]),
            "province": str(row.get("province", row.get("ecoregion", "global"))),
            "season_id": int(row.get("season_id", 0)),
            "environment_class": str(row.get("environment_class", "")),
            "depth_class": str(row.get("depth_class", "")),
            "depth_m": float(row.get("depth_m", 0.0)),
            "turbidity_class": str(row.get("turbidity_class", "")),
            "turbidity_index": float(row.get("turbidity_index", 0.0)),
            "date_range_start": str(row["date_range_start"]),
            "date_range_end": str(row["date_range_end"]),
            "alignment_crs": str(row["alignment_crs"]),
            "patch_size_pixels": int(row.get("patch_size_pixels", PATCH_SIZE_PIXELS)),
            "patch_size_meters": float(row.get("patch_size_meters", DEFAULT_PATCH_SIZE_METERS)),
            "target_origin_x": float(row.get("target_origin_x", 0.0)),
            "target_origin_y": float(row.get("target_origin_y", 0.0)),
            "lowres_satellite": lowres_key,
            "highres_satellite": highres_key,
            "highres_item_ids": row.get("highres_item_ids", []),
            "highres_order_id": "" if pd.isna(row.get("highres_order_id", "")) else str(row.get("highres_order_id", "")),
            "highres_product_bundle": str(row.get("highres_product_bundle", "")),
            "highres_aoi_geojson": row.get("highres_aoi_geojson", {}),
            "lowres_count": int(row.get("lowres_count", 0)),
            "highres_count": int(row.get("highres_count", 1)),
        }

        lowres_count = int(row.get("lowres_count", 0))
        lowres_ok = True
        if lowres_count > 0:
            if _lowres_files_present(sample_dir, lowres_count, lowres_key):
                logger.info(f"Sample {location_id}: {lowres_key} images already on disk, skipping download")
            else:
                lowres_ok = download_lowres_images(
                    sample_metadata,
                    sample_dir,
                    logger,
                    lowres_manager,
                    lowres_count,
                    lowres_key,
                )

        standardized_file = _highres_standardized_file(sample_dir, location_id, highres_key)
        if standardized_file.exists():
            logger.info(f"Sample {location_id}: high-res raster already on disk, skipping download")
            sample_metadata["highres_standardized_file"] = str(standardized_file)
            highres_ok = True
        elif isinstance(highres_manager, GEESatelliteManager):
            highres_ok = download_highres_gee_image(sample_metadata, sample_dir, logger, highres_manager, highres_key)
        else:
            highres_ok = download_highres_planet_order(sample_metadata, sample_dir, logger, highres_manager, highres_key)

        if lowres_ok and highres_ok:
            with open(sample_metadata_file, "w") as file_handle:
                json.dump(sample_metadata, file_handle, indent=2, default=str)
            return True

        return False
    except Exception as exc:
        logger.error(f"Failed to download sample {location_id}: {exc}")
        return False


def download_dataset():
    """Download and preprocess the dataset from a manifest."""
    config = config_download()
    logger = setup_logger("SRDatasetDownloader", config.metadata_dir / "download.log")

    manifest = pd.read_csv(config.manifest_file)

    lowres_managers = {}
    highres_managers = {}

    def get_lowres_manager(key):
        if key not in lowres_managers:
            lowres_managers[key] = build_manager(key, LOWRES_SATELLITES, config)
        return lowres_managers[key]

    def get_highres_manager(key):
        if key not in highres_managers:
            highres_managers[key] = build_manager(key, HIGHRES_SATELLITES, config)
        return highres_managers[key]

    data_dir = ensure_directory(config.data_dir)

    successes = 0
    for _, row in tqdm(manifest.iterrows(), total=len(manifest), desc="Downloading samples"):
        lowres_key = str(row.get("lowres_satellite") or config.lowres_satellite or DEFAULT_LOWRES_SATELLITE)
        highres_key = str(row.get("highres_satellite") or config.highres_satellite or DEFAULT_HIGHRES_SATELLITE)
        lowres_manager = get_lowres_manager(lowres_key)
        highres_manager = get_highres_manager(highres_key)
        if download_sample(row, data_dir, logger, lowres_manager, highres_manager, lowres_key, highres_key):
            successes += 1

    logger.info("Downloaded %s/%s samples", successes, len(manifest))
    print(f"Downloaded {successes}/{len(manifest)} samples")


if __name__ == "__main__":
    download_dataset()
